version: 0.2
phases:
  install:
    commands:
      - pip install cfn-lint
  build:
    commands:
      - cfn-lint --template ./ec2pipe.yml --regions $AWS_REGION
      - aws cloudformation validate-template --template-body file://$(pwd)/ec2pipe.yml
artifacts:
  files:
    - '*'
